table_keys=inclusao, rastreio, seguimento, laboratorio, codigos, evento_adverso
rastreio.filename=config/assets/csv/rastreio.csv
inclusao.filename=config/assets/csv/inclusao.csv
seguimento.filename=config/assets/config/seguimento.csv
laboratorio.filename=config/assets/config/laboratorio.csv
codigos.filename=config/assets/config/codigos.csv
evento_adverso.filename=config/assets/config/evento_adverso.csv